### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by antoniomorais360** [caussourd/aws-s3-bucket-listing#1]
Hello,

I just receiving a blank page with "Amazon S3 Bucket list v 1.1" at the end.

:/

**Comment by caussourd** [comment]
Thank you for reporting the issue. 

It's not necessary to edit the CORS configuration anymore. I updated the README accordingly. 

Your CORS configuration should look like this: 

```
<CORSConfiguration>
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <MaxAgeSeconds>3000</MaxAgeSeconds>
        <AllowedHeader>Authorization</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
```
